<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-10-14T10:06:46Z" name="Default suite" finished-at="2018-10-14T10:06:55Z" duration-ms="8334">
    <groups>
    </groups>
    <test started-at="2018-10-14T10:06:46Z" name="Default test" finished-at="2018-10-14T10:06:55Z" duration-ms="8334">
      <class name="wsm_TrucNa.LoginWSM">
        <test-method is-config="true" signature="access()[pri:0, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:46Z" name="access" finished-at="2018-10-14T10:06:54Z" duration-ms="7274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- access -->
        <test-method signature="case1()[pri:0, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case1" finished-at="2018-10-14T10:06:54Z" duration-ms="169" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login] but found [Working space]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login] but found [Working space]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at wsm_TrucNa.LoginWSM.case1(LoginWSM.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method signature="case2()[pri:1, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case2" finished-at="2018-10-14T10:06:54Z" duration-ms="65" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method signature="case3()[pri:2, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case3" finished-at="2018-10-14T10:06:54Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case3 -->
        <test-method signature="case4()[pri:3, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case4" finished-at="2018-10-14T10:06:54Z" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case4 -->
        <test-method signature="case5()[pri:4, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case5" finished-at="2018-10-14T10:06:54Z" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case5 -->
        <test-method signature="case6()[pri:5, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:54Z" name="case6" finished-at="2018-10-14T10:06:55Z" duration-ms="658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case6 -->
        <test-method signature="case7()[pri:6, instance:wsm_TrucNa.LoginWSM@7494f96a]" started-at="2018-10-14T10:06:55Z" name="case7" finished-at="2018-10-14T10:06:55Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case7 -->
      </class> <!-- wsm_TrucNa.LoginWSM -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
